# Generated by Django 3.1 on 2020-08-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_folder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicitem',
            name='album',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicitem',
            name='artist',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
