# Generated by Django 3.1 on 2020-08-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_folder', '0002_auto_20200815_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicitem',
            name='cover_path',
            field=models.FileField(null=True, upload_to='static/'),
        ),
    ]
